-- tasks table
DROP TABLE IF EXISTS todoapp_java_db.tasks;

CREATE TABLE IF NOT EXISTS todoapp_java_db.tasks (
  id VARCHAR (256) NOT NULL,
  title VARCHAR (256) NOT NULL,
  status ENUM("FINISHED", "UNFINISHED") NOT NULL DEFAULT "UNFINISHED",
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
